### PR TITLE
Implementation of fortify scan to NightlyPipeline

### PR DESCRIPTION
**Pull request by kaanaktas**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CCD-1344

### Change description ###

Implementation of fortify scan to NightlyPipeline

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by MSancaktutar — APPROVED** [review]
LGTM, subject to pipeline library version and fortify-client versions are set to stable latest release.

**Review by MSancaktutar — APPROVED** [review]
LGTM.
Library branch selection will obviously be removed before merging this. Many thanks.

**Review by MSancaktutar — APPROVED** [review]
LGTM - just please remove the branch tag from pipeline library.

**Comment by kaanaktas** [comment]
> LGTM.
> Library branch selection will obviously be removed before merging this. Many thanks.

This is done, library branch tag has been removed.

**Pull request merged**
